CREATE OR REPLACE PACKAGE DAY_1_PKG AS
    PROCEDURE P_run;
END;
/
CREATE OR REPLACE PACKAGE BODY DAY_1_PKG AS
    PROCEDURE P_run
    AS
        lv_temp VARCHAR2 (255 CHAR);
    BEGIN
        NULL;
    END P_run;
END;
/